# Generated by Django 4.2 on 2023-04-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0005_alter_listing_category_alter_listing_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.CharField(
                choices=[
                    ("Electronics", "Electronics"),
                    ("Property", "Property"),
                    ("Fashion", "Fashion"),
                    ("Mobiles", "Mobiles"),
                    ("Furniture", "Furniture"),
                    ("Bikes", "Bikes"),
                    ("Jobs", "Jobs"),
                    ("Cars", "Cars"),
                    ("Books&Sports", "Books&Sports"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="state",
            field=models.CharField(
                choices=[
                    ("MP", "Madhya Pradesh"),
                    ("TN", "Tamil Nadu"),
                    ("HP", "Haryana"),
                    ("ML", "Meghalaya"),
                    ("WB", "West Bengal"),
                    ("AP", "Andhra Pradesh"),
                    ("TS", "Telegana"),
                    ("PB", "Punjab"),
                    ("AS", "Assam"),
                    ("AR", "Arunachal Pradesh"),
                    ("OD", "Odisha"),
                    ("MN", "Manipur"),
                    ("GA", "Goa"),
                    ("TR", "Tripura"),
                    ("UP", "Uttar Pradesh"),
                    ("RJ", "Rajasthan"),
                    ("BR", "Bihar"),
                    ("MZ", "Mizoram"),
                    ("KA", "Karnataka"),
                    ("UK", "Uttarakhand"),
                    ("NL", "Nagaland"),
                    ("JH", "Jharkhand"),
                    ("MH", "Maharashtra"),
                    ("CG", "Chhattisgarh"),
                    ("MI", "Sikkim"),
                    ("KL", "Kerala"),
                    ("GJ", "Gujarat"),
                ],
                max_length=100,
            ),
        ),
    ]
